# Generated by Django 5.1.4 on 2025-06-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tertulia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tertulia_name', models.CharField(max_length=100)),
                ('tertulia_banner', models.ImageField(blank=True, default='fallback.png', upload_to='')),
                ('tertulia_description', models.TextField(blank=True, max_length=450)),
                ('tertulia_address', models.CharField(blank=True, max_length=250, null=True)),
                ('tertulia_horario', models.CharField(max_length=100)),
                ('tertulia_fecha_de_inicio', models.DateField(null=True)),
                ('tertulia_sesiones', models.PositiveSmallIntegerField()),
                ('tertulia_encargado_picture', models.ImageField(blank=True, default='alonso.jpg', upload_to='')),
                ('tertulia_encargado', models.CharField(max_length=100)),
                ('tertulia_lugares', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
