# Generated by Django 5.1.4 on 2025-06-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tertulias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tertulia',
            name='slug',
            field=models.IntegerField(default=0),
        ),
    ]
