# Generated by Django 5.2.1 on 2025-05-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tertulias', '0010_alter_tertulia_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tertulia',
            name='tertulia_banner',
            field=models.ImageField(upload_to='tertulias/'),
        ),
        migrations.AlterField(
            model_name='tertulia',
            name='tertulia_encargado_picture',
            field=models.ImageField(upload_to='tertulias/encargado'),
        ),
    ]
