# Generated by Django 5.1.4 on 2025-05-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tertulias', '0011_alter_tertulia_tertulia_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tertulia',
            name='tertulia_banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='tertulia',
            name='tertulia_encargado_picture',
            field=models.ImageField(blank=True, default='alonso.jpg', upload_to=''),
        ),
    ]
