# Generated by Django 5.1.4 on 2025-06-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tertulias', '0012_alter_tertulia_tertulia_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tertulia',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
