# Generated by Django 5.1.4 on 2025-05-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_curso_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='curso',
            name='curso_encargado_picture',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
